version: '3.7'
services:
  app:
    image: mediaflixspring
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/mediaflix
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=castelao
    networks:
      - springboot-mysql-network
  mysqldb:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=mediaflix
      - MYSQL_ROOT_PASSWORD=castelao
    command: --init-file /data/application/mediaflix.sql
    volumes:
        - ./src/main/resources/mediaflix.sql:/data/application/mediaflix.sql
    networks:
      - springboot-mysql-network
volumes:
  mysql-data:
networks:
  springboot-mysql-network:
    name: springboot-mysql-network
    external: true